#!/bin/bash

## Developed by Seaghán Elliott Walter Collins

# Check for proper usage
if [[ $# != 2 ]]; then
  >&2 echo "Usage; improper arguments"
  exit 1
fi

# Check for memory leaks from each test in the suite
for file in $(cat "$1"); do 
  valgrind --leak-check=summary --error-exitcode=1 $2 < ${file}.in
  if [[ $? != 0 ]]; then 
    echo "memory error on " ${file}
    exit 1
  fi
done

exit 0