#!/bin/bash

## Developed by Seaghán Elliott Walter Collins

# check for proper usage
if [ ! -f "$1" ]; then
	>&2 echo "Usage; suite file could not be read"
	exit 1
elif [[ $# != 2 ]]; then
	>&2 echo "Usage; runSuite requires 2 arguments:"
	>&2 echo "suite file, program file"
	exit 1
elif [ ! -f "$2" ]; then
	>&2 echo "Usage; program file could not be read"
	exit 1
fi

for file in $(cat "$1"); do
	# check for output files
	if [ ! -f ${file}.out ]; then
		>&2 echo "Usage; output file could not be found for test:" ${file}
		exit 1
	fi

	# store output in temp file
	tempfile=$(mktemp)
	if [ -f ${file}.in ] && [ -f ${file}.args ]; then
		($2 $(cat "${file}.args") < ${file}.in) > ${tempfile}
	elif [ -f ${file}.in ]; then
		($2 < ${file}.in) > ${tempfile}
	elif [ -f ${file}.args ]; then
		$2 $(cat "${file}.args") > ${tempfile}
	else
		$2 > "$tempfile"
	fi

	# check for correctness
	if [[ $(cat "$tempfile") != "$(cat ${file}.out)" ]]; then
		echo "Test failed: "${file}
		echo "Args:"
		if [ -f ${file}.args ]; then
			cat ${file}.args
		fi
		echo "Input:"
		if [ -f ${file}.in ]; then
			cat ${file}.in
		fi
		echo "Expected:"
		cat ${file}.out
		echo "Actual:"
		cat "$tempfile"
		
	fi
	rm "$tempfile"
done
