#!/bin/bash

#check for proper usage
if [[ $# != 2 ]]; then
	>&2 echo "Usage; produceOutputs requires two arguments: suite file, program file"
	exit 1
elif [[ ! -f "$1" ]]; then
	>&2 echo "Usage; cannot locate suite file"
	exit 1
elif [[ ! -f "$2" ]]; then
	>&2 echo "Usage; cannot locate program file"
	exit 1
fi

for file in $(cat "$1"); do

	if [ -f ${file}.args ] && [ -f ${file}.in ]; then
		($2 $(cat ${file}.args) < ${file}.in) > ${file}.out
	elif [ -f ${file}.args ]; then
		$2 $(cat ${file}.args) > ${file}.out
	elif [ -f ${file}.in ]; then
		$2 < ${file}.in > ${file}.out
	else
		$2 > ${file}.out
	fi
done
